// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM15ytqzoLDQAJ99uTcWp1TZPDsOp09jQ',
    appId: '1:884674446322:web:b4c4d382f575fcb9fee16b',
    messagingSenderId: '884674446322',
    projectId: 'e-wallet-368e5',
    authDomain: 'e-wallet-368e5.firebaseapp.com',
    storageBucket: 'e-wallet-368e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLk1A92M3OyvWjBCcYP9aG7tKOMr4y-7A',
    appId: '1:884674446322:android:03047651dbd1f5cbfee16b',
    messagingSenderId: '884674446322',
    projectId: 'e-wallet-368e5',
    storageBucket: 'e-wallet-368e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhBfNG_Ng_XJOjwxSlmMlaRaEsvYAiG-U',
    appId: '1:884674446322:ios:c6be7230fb3646a6fee16b',
    messagingSenderId: '884674446322',
    projectId: 'e-wallet-368e5',
    storageBucket: 'e-wallet-368e5.appspot.com',
    iosBundleId: 'com.example.ewallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhBfNG_Ng_XJOjwxSlmMlaRaEsvYAiG-U',
    appId: '1:884674446322:ios:c6be7230fb3646a6fee16b',
    messagingSenderId: '884674446322',
    projectId: 'e-wallet-368e5',
    storageBucket: 'e-wallet-368e5.appspot.com',
    iosBundleId: 'com.example.ewallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM15ytqzoLDQAJ99uTcWp1TZPDsOp09jQ',
    appId: '1:884674446322:web:76d284cc04c25e83fee16b',
    messagingSenderId: '884674446322',
    projectId: 'e-wallet-368e5',
    authDomain: 'e-wallet-368e5.firebaseapp.com',
    storageBucket: 'e-wallet-368e5.appspot.com',
  );
}
